Repository ministryofjustice/laa-crime-application-store, pull requests merged in 2024-04, with the labels that each got.

#112 CRM457-1305: Skeleton for new notification service
  Pipfile
  Pipfile.lock
  alembic/versions/f9a2f1c1d378_create_subscriber_table.py
  laa_crime_application_store_app/internal/notifier.py
  laa_crime_application_store_app/main.py
  laa_crime_application_store_app/models/subscriber_schema.py
  laa_crime_application_store_app/routers/v1/application.py
  laa_crime_application_store_app/routers/v1/subscriber.py
  laa_crime_application_store_app/schema/subscriber.py
  laa_crime_application_store_app/services/v1/notification_service.py
  tests/internal/notifier_test.py
  tests/routers/conftest.py
  tests/routers/v1/application_test.py
  tests/routers/v1/subscriber_test.py
Labels: ready-to-review

#122 Fix deployment issues
  .circleci/config.yml
  app/controllers/health_controller.rb
  helm_deploy/values-production.yaml
  helm_deploy/values-uat.yaml
Labels: ready-to-review

#123 CRM457-1327: More fixes
  .circleci/config.yml
  app/controllers/health_controller.rb
  app/jobs/notify_subscriber.rb
  app/services/tokens/verification_service.rb
  config/puma.rb
  helm_deploy/values-production.yaml
  helm_deploy/values-uat.yaml
  spec/jobs/notify_subscriber_spec.rb
  spec/requests/create_submission_spec.rb
Labels: ready-to-review

#125 CRM457-1146: Add authorization rules
  app/controllers/V1/submissions_controller.rb
  app/controllers/V1/subscribers_controller.rb
  app/controllers/application_controller.rb
  app/controllers/health_controller.rb
  app/services/authorization/rules.rb
  app/services/authorization_service.rb
  app/services/submissions/update_service.rb
  spec/requests/authentication_spec.rb
  spec/requests/authorization_spec.rb
  spec/requests/delete_subscriber_spec.rb
  spec/requests/update_submission_spec.rb
Labels: ready-to-review

#127 Use roles instead of knowing specific IDs
  app/services/tokens/verification_service.rb
  helm_deploy/templates/deployment-worker.yaml
  helm_deploy/templates/deployment.yaml
  spec/requests/authentication_spec.rb
  spec/requests/authorization_spec.rb
Labels: ready-to-review, approved

#126 Amendments from local setup
  .circleci/config.yml
  .env.development
  Gemfile.lock
  Procfile.dev
  app/mailers/application_mailer.rb
  bin/dev
  config/application.rb
  config/environments/development.rb
  config/environments/production.rb
  config/environments/test.rb
  config/routes.rb
  helm_deploy/templates/deployment.yaml
  spec/spec_helper.rb
Labels: approved

#132 Change labels on worker deployment
  helm_deploy/templates/deployment-worker.yaml
Labels: approved

#130 App store - add environment to sentry config
  config/initializers/sentry.rb
  helm_deploy/templates/deployment-worker.yaml
  helm_deploy/templates/deployment.yaml
  helm_deploy/values-development.yaml
  helm_deploy/values-production.yaml
  helm_deploy/values-uat.yaml
Labels: ready-to-review

#118 Fix Old and Incorrect Namespace/Repo References
  .circleci/config.yml
  .github/CODEOWNERS
  postman/README.md
Labels: approved

#134 Send payload inside webhook request
  app/jobs/notify_subscriber.rb
  spec/jobs/notify_subscriber_spec.rb
Labels: ready-to-review

#133 CRM457-917: Add circleci config for e2e tests
  .circleci/config.yml
Labels: approved

#136 Disable modsec in dev
  helm_deploy/values-development.yaml
Labels: ready-to-review
