Repository ministryofjustice/laa-crime-application-store, pull requests merged in 2024-12, with the labels that each got.

#338 CRM457-2322 part 1: Pull anonymised records from prod to localhost
  Gemfile
  Gemfile.lock
  README.md
  bin/delete_anonymised
  bin/download_anonymised
  lib/tasks/anonymised.rake
  spec/lib/tasks/anonymised_data_spec.rb
Labels: approved

#339 CRM457-2221: Remove redundant pub-sub mechanism
  .env.development
  README.md
  app/controllers/V1/submissions_controller.rb
  app/controllers/V1/subscribers_controller.rb
  app/jobs/expire_sendbacks.rb
  app/jobs/notify_subscriber.rb
  app/models/subscriber.rb
  app/services/authorization/rules.rb
  app/services/notification_service.rb
  app/services/submissions/update_service.rb
  app/services/tokens/generation_service.rb
  config/routes.rb
  db/migrate/20241206171615_delete_subscriber.rb
  db/schema.rb
  helm_deploy/templates/deployment-worker.yaml
  helm_deploy/templates/deployment.yaml
  helm_deploy/values-development.yaml
  helm_deploy/values-production.yaml
  helm_deploy/values-uat.yaml
  lib/tasks/adjust.rake
  spec/factories/subscribers.rb
  spec/jobs/expire_sendbacks_spec.rb
  spec/jobs/notify_subscriber_spec.rb
  spec/lib/tasks/adjust_status_spec.rb
  spec/requests/authorization_spec.rb
  spec/requests/create_submission_spec.rb
  spec/requests/create_subscriber_spec.rb
  spec/requests/delete_subscriber_spec.rb
  spec/requests/update_submission_spec.rb
Labels: approved

#340 CRM457-2322 part 2: Push record to UAT
  README.md
  bin/delete_anonymised
  bin/download_anonymised
  lib/tasks/anonymised.rake
  spec/lib/tasks/anonymised_data_spec.rb
Labels: ready-to-review, approved

#344 CRM457-2335: Risk and value setting
  Gemfile
  Gemfile.lock
  app/controllers/V1/submissions/searches_controller.rb
  app/controllers/V1/submissions_controller.rb
  app/models/submission.rb
  app/services/submissions/search_service.rb
  db/migrate/20241211102459_make_risk_optional.rb
  db/schema.rb
  spec/requests/create_submission_spec.rb
  spec/requests/show_submission_spec.rb
  spec/requests/update_submission_metadata_spec.rb
  spec/services/submissions/search_service_spec.rb
Labels: approved

#345 Use bugfixed gem version
  Gemfile
  Gemfile.lock
Labels: approved

#346 CRM457-2339: Wrap creation calls in a transaction
  app/services/submissions/creation_service.rb
  spec/requests/create_submission_spec.rb
Labels: approved

#347 Increase anomaly threshold
  helm_deploy/templates/metabase/ingress.yaml
Labels: ready-to-review

#348 Get schema file under control
  config/initializers/schema_fix.rb
  db/schema.rb
Labels: approved

#350 CRM457-2217: Stop looking at the events column
  app/jobs/expire_sendbacks.rb
  app/models/submission.rb
  app/services/submissions/event_addition_service.rb
  app/services/submissions/search_service.rb
  db/migrate/20240806130123_backfill_disbursement_position.rb
  db/migrate/20240819134005_backfill_work_item_position.rb
  db/migrate/20241213150530_minimise_use_of_events.rb
  db/schema.rb
  db/views/autogrant_events_v03.sql
  db/views/searches_v08.sql
  db/views/submissions_by_date_v04.sql
  lib/data_migration_tools/disbursement_position_updater.rb
  lib/data_migration_tools/work_item_position_updater.rb
  lib/tasks/adjust.rake
  lib/tasks/check_autogrants.rake
  lib/tasks/fixes.rake
  lib/tasks/missing_version_timestamps.rake
  spec/factories/caseworker_history_events.rb
  spec/factories/submissions.rb
  spec/lib/data_migration_tools/disbursement_position_updater_spec.rb
  spec/lib/data_migration_tools/work_item_position_updater_spec.rb
  spec/lib/tasks/adjust_fix_expired_data.rb
  spec/lib/tasks/adjust_fix_expired_spec.rb
  spec/lib/tasks/adjust_fix_provider_updated_data.rb
  spec/lib/tasks/adjust_fix_provider_updated_spec.rb
  spec/lib/tasks/adjust_status_spec.rb
  spec/lib/tasks/adjust_update_state_data.rb
  spec/lib/tasks/adjust_update_state_spec.rb
  spec/lib/tasks/auto_fix_mismatched_references_spec.rb
  spec/lib/tasks/check_autogrants_spec.rb
  spec/lib/tasks/find_mismatched_references_spec.rb
  spec/lib/tasks/fixes_spec.rb
  spec/postgres_views/autogrant_events_spec.rb
  spec/postgres_views/eod_assignment_count_spec.rb
  spec/postgres_views/submissions_by_date_spec.rb
  spec/requests/submissions_search_spec.rb
Labels: approved

#352 CRM457-2154: Filter rake task for adding high value
  lib/tasks/CRM457_2154.rake
Labels: approved

#353 CRM457-2154: High value rake task - actually update the application hash
  lib/tasks/CRM457_2154.rake
Labels: approved

#355 Crm457-2353: Rubocop cleanup
  .rubocop.yml
  config/application.rb
  config/environments/production.rb
  config/initializers/govuk_notify.rb
  config/initializers/lograge.rb
  config/initializers/prometheus.rb
  config/initializers/schema_fix.rb
  config/initializers/sentry.rb
  config/initializers/sidekiq.rb
  config/routes.rb
Labels: approved
