Repository ministryofjustice/laa-crime-application-store, pull requests merged in 2024-05, with the labels that each got.

#139 Stop running postman tests
  .circleci/config.yml
  postman/README.md
  postman/collections/Application.postman_collection.json
  postman/collections/Ping.postman_collection.json
  postman/environments/dev.postman_environment.json
  postman/environments/local.postman_environment.json
  postman/environments/uat.postman_environment.json
Labels: ready-to-review

#143 CRM457-1456: Add horizontal pod autoscaler (HPA) config
  helm_deploy/templates/hpa-worker.yaml
  helm_deploy/templates/hpa.yaml
  helm_deploy/values-development.yaml
  helm_deploy/values-production.yaml
  helm_deploy/values-uat.yaml
Labels: approved

#149 CRM457-1332-Adds deployment for Metabase
  helm_deploy/templates/ingress.yaml
  helm_deploy/templates/metabase/deployment.yaml
  helm_deploy/templates/metabase/ingress.yaml
  helm_deploy/templates/metabase/service.yaml
  helm_deploy/values-development.yaml
  helm_deploy/values-production.yaml
  helm_deploy/values-uat.yaml
Labels: question, approved
